name: Release on README Update

on:
  push:
    paths:
      - 'README.md'  # 只在 README.md 文件变更时触发

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. 安装依赖
    - name: Install dependencies
      run: npm install

    # 4. 构建项目
    - name: Build project
      run: npm run dev
      run: npm run build

    # 5. 生成版本号（基于日期时间）
    - name: Generate Version
      id: version
      run: |
        TIMESTAMP=$(date +%Y.%m.%d-%H%M)
        echo "version=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "Generated version: $TIMESTAMP"

    # 6. 准备发布文件
    - name: Prepare release assets
      run: |
        # 创建时间戳
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        
        # 打包构建产物
        tar -czf blog-build-$TIMESTAMP.tar.gz ./dist
        
        # 打包纯净源码
        tar -czf source-code-$TIMESTAMP.tar.gz \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='.github' \
          .
        
        # 创建版本信息文件
        echo "Version: ${{ steps.version.outputs.version }}" > version.txt
        echo "Build Date: $(date)" >> version.txt
        echo "Commit: ${{ github.sha }}" >> version.txt
        echo "Triggered by: README.md update" >> version.txt

    # 7. 创建 GitHub Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}  # 使用生成的版本号
        release_name: "Release ${{ steps.version.outputs.version }} (README Update)"
        body: |
          This release was automatically triggered by an update to README.md.
          
          **Details:**
          - Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          - Build Date: $(date)
          - Trigger File: README.md
        draft: false
        prerelease: true

    # 8. 上传 Release 资产
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./blog-build-*.tar.gz
        asset_name: blog-build-${{ steps.version.outputs.version }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Source Code
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./source-code-*.tar.gz
        asset_name: source-code-${{ steps.version.outputs.version }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Version Info
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./version.txt
        asset_name: build-info-${{ steps.version.outputs.version }}.txt