name: Vue 2 Production Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    # 使用 GitHub 托管的 macOS 环境（兼容性最佳）
    runs-on: macos-12
    timeout-minutes: 20  # 防止无限卡住

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # 使用 Node 14 LTS（Vue2 官方推荐版本）
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.21.3'  # 指定精确版本
        cache: 'npm'
        
    # 最小化依赖安装（跳过 peerDependencies）
    - name: Install core dependencies
      run: |
        npm install --no-package-lock --no-save \
          vue@^2.5.2 \
          vue-loader@^13.3.0 \
          vue-template-compiler@^2.5.2 \
          webpack@^3.6.0
        
    # 选择性安装其他依赖
    - name: Install project dependencies
      run: |
        npm install --legacy-peer-deps --no-audit --no-optional
        
    # 尝试构建（带详细日志）
    - name: Build project
      run: |
        npm run build --verbose
        
    # 验证构建结果
    - name: Verify build output
      run: |
        echo "构建目录内容:"
        ls -la dist/
        [ -f dist/index.html ] || exit 1
        
    # 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1