name: Vue 2 Production CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-24  # 使用较旧的 Ubuntu 版本获取兼容的 OpenSSL
    strategy:
      matrix:
        # 使用 Node.js 12.x (Vue2/Webpack3 官方支持的最低版本)
        node-version: [12.22.12]  # 指定精确版本确保兼容性

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 配置环境变量解决兼容性问题
    - name: Configure environment
      run: |
        echo "CI=true" >> $GITHUB_ENV
        echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV

    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          node_modules
          .npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps --no-audit
        # 可选：修复已知兼容性问题
        npm install webpack@3.12.0

    - name: Run unit tests
      run: npm run unit

    - name: Build production bundle
      run: npm run build

    - name: Verify build output
      run: |
        ls -la dist/
        [ -f dist/index.html ] || exit 1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-dist
        path: dist/
        retention-days: 3

    # 可选：部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && success()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true