name: Vue 2 Production CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 使用 Node 14.x 确保 Vue2 + Webpack3 兼容性
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 解决 Webpack 3 在 Node 14+ 的 OpenSSL 兼容性问题
    - name: Configure legacy OpenSSL
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          node_modules
          .npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: |
        npm ci --legacy-peer-deps
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"

    - name: Run unit tests
      run: npm run unit
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"

    - name: Build production bundle
      run: npm run build
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"

    # 使用最新版 artifacts 上传
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-dist
        path: dist/
        retention-days: 3

    # 可选：部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && success()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true