name: Vue 2 Release Build

on:
  workflow_dispatch: # 手动触发
  release:
    types: [created] # 当创建新发布时自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 获取完整提交历史
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        cache: 'npm'
        
    - name: Environment diagnostics
      run: |
        echo "构建时间: $(date)"
        echo "Node.js版本: $(node --version)"
        echo "npm版本: $(npm --version)"
        echo "提交哈希: ${{ github.sha }}"
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --no-audit --no-optional
        echo "依赖列表:"
        npm list --depth=0
        
    - name: Build production bundle
      run: |
        echo "开始生产构建..."
        npm run build --verbose
        
        echo "构建输出:"
        du -sh dist/*
        
    - name: Package build artifacts
      run: |
        cd dist
        zip -r ../release-${{ github.run_id }}.zip .
        echo "打包完成!"
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release-${{ github.run_id }}.zip
        asset_name: release-build-${{ github.run_id }}.zip
        asset_content_type: application/zip
        
    - name: Deploy to GitHub Pages (可选)
      if: success()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        
    - name: Create build report
      if: always()
      run: |
        echo "构建状态: ${{ job.status }}" > build-report.txt
        echo "运行ID: ${{ github.run_id }}" >> build-report.txt
        echo "提交: ${{ github.sha }}" >> build-report.txt
        echo "触发者: ${{ github.actor }}" >> build-report.txt
        date >> build-report.txt
        
    - name: Upload build report
      uses: actions/upload-artifact@v4
      with:
        name: build-report
        path: build-report.txt
        retention-days: 7