name: Vue 2 Minimal Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    # 使用最轻量级的 Windows 环境
    runs-on: windows-latest
    timeout-minutes: 15  # 防止无限等待
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 跳过 Node.js 安装，直接使用系统 Node
    - name: Use built-in Node.js
      run: |
        node --version
        npm --version
        
    # 最小化依赖安装
    - name: Install essential dependencies only
      run: |
        # 仅安装最核心的依赖
        npm install vue@^2.5.2
        npm install webpack@^3.6.0
        npm install vue-loader@^13.3.0
        npm install vue-template-compiler@^2.5.2
        
    # 尝试直接调用构建脚本
    - name: Run build script directly
      run: |
        node build/build.js
        
    # 验证结果
    - name: Check build output
      run: |
        if (Test-Path -Path dist) {
          Write-Host "构建成功! 文件列表:"
          Get-ChildItem -Path dist -Recurse | Select-Object Name, Length
        } else {
          Write-Host "构建失败: dist 目录不存在"
          Exit 1
        }
        
    # 上传结果
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        retention-days: 1